sql
CREATE TABLE CUSTOMERS (
  customer_id NUMBER PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  region VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCTS (
  product_id NUMBER PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL
);
CREATE TABLE TRANSACTIONS (
  transaction_id NUMBER PRIMARY KEY,
  customer_id NUMBER, 
  product_id NUMBER,
  sale_date DATE NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (customer_id),
  CONSTRAINT fk_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCTS (product_id)
);Inserting values in the created tables
     CUSTOMERS
INSERT INTO CUSTOMERS VALUES (1001,'Keza Nisha', 'Kigali');
INSERT INTO CUSTOMERS VALUES (1002,'Mucyo Brian', 'Kicukiro');
INSERT INTO CUSTOMERS VALUES (1003,'Mwiza Lynn', 'Bugesera');
     PRODUCTS
INSERT INTO PRODUCTS VALUES (2001,'Nike', 'shoes');
INSERT INTO PRODUCTS VALUES (2002, 'Versace', 'dress');
INSERT INTO PRODUCTS VALUES (2003,'YSL', 'PERFUME');
     TRANSACTIONS
INSERT INTO TRANSACTIONS VALUES (3001,1001,2001,'08-03-2025', 3000.03);
INSERT INTO TRANSACTIONS VALUES (3002,1002,2002,'11-07-2025', 6000.00);
INSERT INTO TRANSACTIONS VALUES (3003,1003,2003,'17-11-2025', 8000.03);

  
  
