sql
CREATE TABLE CUSTOMERS (
  customer_id NUMBER PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  region VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCTS (
  product_id NUMBER PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL
);
CREATE TABLE TRANSACTIONS (
  transaction_id NUMBER PRIMARY KEY,
  customer_id NUMBER, 
  product_id NUMBER,
  sale_date DATE NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_CUSTOMER FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (customer_id),
  CONSTRAINT fk_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCTS (product_id)
);
  
  
  
